---
- name: install apache on node3
  hosts: node3
  become: true
  become_user: root
  tasks:
  - name: install httpd package
    yum:
     name: thttpd
     state: latest
  - name: start and enable httpd service at boot
    service:
      name: httpd
      state: started
      enabled: true
  - name: install firewalld
    yum:
      name: firewalld
      state: latest
  - name: start and enable firewalld service at boot
    service:
      name : firewalld
      state: started
      enabled: true
  - name: allow http in firewalld
    firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: true
