- hosts: all
  become: true
  tasks:
   - copy:
        content: "Content Changed"
        dest: /var/www/html/index.html
     notify: restart_apache
  handlers:
    - name: restart_apache
      service:
        name: httpd
        status: restarted
