- hosts: all
  become: true
  tasks:
    - name: copy the content
      copy:
        content: Hello DevOps
        dest: /var/www/html/index.html
      notify: restart_apache
  handlers:
  - name: restart_apache
    service: 
      name: httpd
      state: restarted
